### PR TITLE
Removed build dir in go server

### PR DESCRIPTION
**Pull request by gdsoumya**
Signed-off-by: gdsoumya <gdsoumya@gmail.com>

### CODE REVIEW

**Comment by ispeakc0de** [comment]
test

**Comment by ispeakc0de** [comment]
test++

**Comment by gdsoumya** [comment]
hekllo

**Comment by gdsoumya** [comment]
Hello

**Comment by gdsoumya** [comment]
hello

**Comment by gdsoumya** [comment]
hello

**Comment by gdsoumya** [comment]
helo

**Comment by gdsoumya** [comment]
hello

**Comment by gdsoumya** [comment]
Hello World

**Comment by gdsoumya** [comment]
Test

**Comment by gdsoumya** [comment]
Tesstst

**Comment by gdsoumya** [comment]
Test Again

**Comment by gdsoumya** [comment]
Hello World

**Comment by gdsoumya** [comment]
gooo

**Comment by gdsoumya** [comment]
Let's Go

**Comment by gdsoumya** [comment]
Y?

**Comment by gdsoumya** [comment]
Try Harder

**Comment by gdsoumya** [comment]
Hello

**Comment by gdsoumya** [comment]
hello

**Comment by gdsoumya** [comment]
hello

**Comment by gdsoumya** [comment]
hello

**Comment by gdsoumya** [comment]
Tester

**Comment by gdsoumya** [comment]
Hello

**Comment by gdsoumya** [comment]
Hi

**Comment by gdsoumya** [comment]
Hello

**Comment by gdsoumya** [comment]
Hi

**Comment by gdsoumya** [comment]
Hi

**Comment by gdsoumya** [comment]
Hello

**Comment by gdsoumya** [comment]
hello

**Comment by gdsoumya** [comment]
Hi

**Comment by gdsoumya** [comment]
Hi

**Comment by gdsoumya** [comment]
Hello

**Comment by gdsoumya** [comment]
Hi

**Comment by gdsoumya** [comment]
Hi

**Comment by gdsoumya** [comment]
Hello

**Comment by gdsoumya** [comment]
Hui

**Comment by gdsoumya** [comment]
hello

**Comment by gdsoumya** [comment]
Hi

**Comment by gdsoumya** [comment]
Hello

**Comment by gdsoumya** [comment]
Hi

**Comment by gdsoumya** [comment]
Hui

**Comment by gdsoumya** [comment]
Hello

**Comment by gdsoumya** [comment]
Hello

**Comment by gdsoumya** [comment]
Hifd

**Comment by gdsoumya** [comment]
Hello

**Comment by gdsoumya** [comment]
Hui

**Comment by gdsoumya** [comment]
Hefdf

**Comment by gdsoumya** [comment]
hefhhefd

**Comment by gdsoumya** [comment]
fdsfsdf

**Comment by gdsoumya** [comment]
HelloWorld

**Comment by gdsoumya** [comment]
dsgdfgdfgdf

**Comment by gdsoumya** [comment]
fdsgsgdfgfk

**Pull request closed without merging**
